#:schema node_modules/wrangler/config-schema.json
name = "sublink-worker-1"
main = "src/index.js"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "a9866bc30a34430bbcdfd8556b4251fd" }
]
